# GitHub Action for Laravel with MySQL
name: Testing
on: [push, pull_request]
jobs:
  laravel:
    name: Laravel 8.2
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    # services:
    #   mysql:
    #     image: mysql:8
    #     env:
    #       MYSQL_ALLOW_EMPTY_PASSWORD: false
    #       MYSQL_ROOT_PASSWORD: password
    #       MYSQL_DATABASE: laravel
    #       MYSQL_PASSWORD: password
    #     ports:
    #       - 3306/tcp
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug #optional
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Set up MySQL database and user
        run: |
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};"
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';"
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${DB_DATABASE}.* TO '${DB_USERNAME}'@'%';"
          sudo mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"
      - name: Test Database Connection
        run: |
          sudo mysql -h 127.0.0.1 -P ${DB_PORT} -u ${DB_USERNAME} -p${DB_PASSWORD} -e "SHOW DATABASES;"
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Testing Code
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
      - name: Run PHP CodeSniffer (Linter)
        run: |
            composer require --dev squizlabs/php_codesniffer
            vendor/bin/phpcs --standard=PSR12 app/
      - name: Clear Config
        run: php artisan config:clear
      - name: NPM install
        run: |
            npm install
            npm run build
      - name: Run Migration
        run: php artisan migrate --force -v
      - name: Run Seeder
        run: php artisan db:seed
      - name: Test with phpunit
        run: | 
            composer require --dev phpunit/phpunit
            echo $(sudo pwd)
            ./vendor/bin/pest
      - name: Run Test suite
        run: php artisan test
      - name: Send Telegram Notification
        env:
            TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_REF: ${{ github.ref }}
            GITHUB_SHA: ${{ github.sha }}
        run: |
              MESSAGE="🔔 Repository *$GITHUB_REPOSITORY* baru saja di perbarui $GITHUB_ACTOR. 
              Branch: $GITHUB_REF
              Commit: [$GITHUB_SHA:0:7](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)"
              
              curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
                -d chat_id=$TELEGRAM_CHAT_ID \
                -d text="$MESSAGE" \
                -d parse_mode="Markdown"